version: 2

sources:
  - name: jaffle_shop
    database: dbt-tutorial
    tables:
      - name: customers
      - name: orders
        meta:
          elementary:
            timestamp_column: "_etl_loaded_at"
        tests:
          - elementary.volume_anomalies
          - elementary.all_columns_anomalies:
              column_anomalies:
                - null_count
                - missing_count
                - zero_count
        columns:
          - name: USER_ID
            tests:
              - elementary.column_anomalies
